In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sys



In [ ]:
# The training data.
X = np.array([
[0, 0],
[0, 1],
[1, 0],
[1, 1]
])
# The labels for the training data.
y = np.array([
[0],
[1],
[1],
[0]
])


In [ ]:
W11 = np.asarray([1,1])
W12 = np.asarray([1,1])
W2 = np.asarray([-1,1])
B1 = np.asarray([-1.5,-0.5])
B2 = np.asarray([-0.5])

In [3]:
W11

array([1, 1])

In [4]:
W12

array([1, 1])

In [5]:
B1


array([-1.5, -0.5])

In [6]:
B2

array([-0.5])

In [7]:
x=X[0]
print(x)

[0 0]


In [8]:
len(W11)

2

In [10]:
def summation(x,Wt1,Wt2,Bs):
  sumh=[0,0]
  for i in range(len(x)):
      sumh[i]=(x[0]*Wt1[i]+x[1]*Wt2[i])+Bs[i]
  return sumh



In [15]:
sumv=summation(x,W11,W12,B1)

In [16]:
print(sumv)

[-1.5, -0.5]


In [19]:
def Heaviside (net):
    if net >= 0:
      return 1
    else:
        return 0

In [20]:
hidden=[0,0]
for i in range(len(sumv)):
     hidden[i]=Heaviside(sumv[i])

In [21]:
print(hidden)

[0, 0]


In [22]:
sumo=np.dot(hidden,W2)+B2[0]
y_pred=Heaviside(sumo)


In [23]:
 print(y_pred)

0


In [26]:
y_pred=[]
for i in range(X.shape[0]):
     x=X[i]
     sumv=summation(x,W11,W12,B1)
      hidden=[0,0]
      for i in range(len(sumv)):
          hidden[i]=Heaviside(sumv[i])
      sumo=np.dot(hidden,W2)+B2[0]
      y_pred.append(Heaviside(sumo))

IndentationError: ignored

In [ ]:
y_pred
